<project xmlns="http://maven.apache.org/POM/4.0.0" 
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    
    <parent>
        <groupId>com.slytechs.jnet</groupId>
        <artifactId>jnet-sdk-parent</artifactId>
        <version>0.2.0-SNAPSHOT</version>
        <relativePath>../jnet-sdk/pom.xml</relativePath> 
    </parent>
    
    <groupId>com.slytechs.jnet.core</groupId>
    <artifactId>core-api</artifactId>
    <name>Core SDK - Core API</name>
    <description>Core network utilities and packages</description>

    <dependencies>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <argLine>
                        --add-opens com.slytechs.jnet.core.api/com.slytechs.jnet.core.api.memory=ALL-UNNAMED
                    </argLine>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>